### PR TITLE
 Rename the text of the buttons #437

### PR DESCRIPTION
**Pull request by techmannih**
issue  #437
  

close #437

type of change 

 Rename the text of the buttons from "Undo move "  to  " Take back"

### CODE REVIEW

**Comment by programarivm** [comment]
Thanks @techmannih for contributing to the ChesslaBlab community!

Can you please send these changes to the chesslablab/react-chess repo instead? Let me also point out that the chesslablab/react-chess has recently been updated.

Keep it up,

**Comment by techmannih** [comment]
I m not able to search "Undo move" button in chesslablab/react-chess

**Comment by programarivm** [comment]
No worries, thanks for the help!

**Comment by programarivm** [comment]
Thank you @techmannih, the buttons changed after a recent update. I hope this will help https://github.com/chesslablab/react-chess/issues/437#issuecomment-1619191530

**Pull request closed without merging**
